import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import { TipCalculator } from "./tip-calculator";

test("TipCalculator", () => {
  const { asFragment } = render(<TipCalculator />);

  expect(asFragment()).toMatchInlineSnapshot(`
<DocumentFragment>
  <div
    class=""
  >
    <span
      class=""
    >
      <label
        class=""
        data-baseweb="form-control-label"
      >
        Subtotal
      </label>
    </span>
    <div
      class=""
      data-baseweb="form-control-container"
    >
      <div
        class=""
        data-baseweb="input"
      >
        <div
          class=""
          data-baseweb="base-input"
        >
          <input
            aria-invalid="false"
            aria-required="false"
            autocomplete="on"
            class=""
            inputmode="decimal"
            name=""
            placeholder=""
            type="text"
            value=""
          />
        </div>
      </div>
    </div>
    <span
      class=""
    >
      <label
        class=""
        data-baseweb="form-control-label"
      >
        Tax
      </label>
    </span>
    <div
      class=""
      data-baseweb="form-control-container"
    >
      <div
        class=""
      >
        <div
          class=""
          data-baseweb="input"
        >
          <div
            class=""
          >
            $
          </div>
          <div
            class=""
            data-baseweb="base-input"
          >
            <input
              aria-invalid="false"
              aria-required="false"
              autocomplete="on"
              class=""
              inputmode="decimal"
              name=""
              placeholder=""
              type="text"
              value=""
            />
          </div>
        </div>
        <div
          class=""
          data-baseweb="input"
        >
          <div
            class=""
            data-baseweb="base-input"
          >
            <input
              aria-invalid="false"
              aria-required="false"
              autocomplete="on"
              class=""
              inputmode="decimal"
              name=""
              placeholder=""
              type="text"
              value=""
            />
          </div>
          <div
            class=""
          >
            %
          </div>
        </div>
      </div>
    </div>
    <span
      class=""
    >
      <label
        class=""
        data-baseweb="form-control-label"
      >
        Tip
      </label>
    </span>
    <div
      class=""
      data-baseweb="form-control-container"
    >
      <div
        class=""
      >
        <div
          class=""
          data-baseweb="input"
        >
          <div
            class=""
          >
            $
          </div>
          <div
            class=""
            data-baseweb="base-input"
          >
            <input
              aria-invalid="false"
              aria-required="false"
              autocomplete="on"
              class=""
              inputmode="decimal"
              name=""
              placeholder=""
              type="text"
              value=""
            />
          </div>
        </div>
        <div
          class=""
          data-baseweb="input"
        >
          <div
            class=""
            data-baseweb="base-input"
          >
            <input
              aria-invalid="false"
              aria-required="false"
              autocomplete="on"
              class=""
              inputmode="decimal"
              name=""
              placeholder=""
              type="text"
              value=""
            />
          </div>
          <div
            class=""
          >
            %
          </div>
        </div>
      </div>
    </div>
    <span
      class=""
    >
      <label
        class=""
        data-baseweb="form-control-label"
      >
        Total
      </label>
    </span>
    <div
      class=""
      data-baseweb="form-control-container"
    >
      <div
        class=""
        data-baseweb="input"
      >
        <div
          class=""
          data-baseweb="base-input"
        >
          <input
            aria-invalid="false"
            aria-required="false"
            autocomplete="on"
            class=""
            inputmode="text"
            name=""
            placeholder=""
            type="text"
            value=""
          />
        </div>
      </div>
    </div>
    <span
      class=""
    >
      <label
        class=""
        data-baseweb="form-control-label"
      >
        Per person
      </label>
    </span>
    <div
      class=""
      data-baseweb="form-control-container"
    >
      <div
        class=""
      >
        <div
          class=""
          data-baseweb="input"
        >
          <div
            class=""
          >
            $
          </div>
          <div
            class=""
            data-baseweb="base-input"
          >
            <input
              aria-invalid="false"
              aria-required="false"
              autocomplete="on"
              class=""
              inputmode="text"
              name=""
              placeholder=""
              type="text"
              value=""
            />
          </div>
        </div>
        <div
          class=""
          data-baseweb="input"
        >
          <div
            class=""
            data-baseweb="base-input"
          >
            <input
              aria-invalid="false"
              aria-required="false"
              autocomplete="on"
              class=""
              inputmode="numeric"
              name=""
              placeholder=""
              type="text"
              value="1"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</DocumentFragment>
`);
});
